name: Release

on:
  workflow_dispatch:

env:
  FLOX_DISABLE_METRICS: true
  REGISTRY: ghcr.io
  VERSION: latest

permissions:
  contents: read

jobs:
  package:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Package
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Checkout source code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Flox
        uses: flox/install-flox-action@8c71d71672ea52e1494b168ac0f27d46b96068be # v2.5.2

      - name: Login to Docker
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}

      - name: Build and publish Template OCI artifacts
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: task templates:publish VERSION=${{ env.VERSION }}

      - name: Sign Template OCI artifacts
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: task templates:sign VERSION=${{ env.VERSION }}

      - name: Build and publish Template Catalog OCI artifact
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: task catalog:publish VERSION=${{ env.VERSION }}

      - name: Sign Template Catalog OCI artifact
        uses: flox/activate-action@7065dcbe5583b7b015f07a8ebd49d7266e3053e8 # v1.1.1
        with:
          command: task catalog:sign VERSION=${{ env.VERSION }}
